pub mod gua;
pub mod cang_sea;
pub mod project_context;
pub mod bagua;
pub mod lianshan;
pub mod deviation;
pub mod embedding;
pub mod semantic;
pub mod yin_checker;
pub mod constraint_text;
pub mod context_metabolism;
pub mod hanzi_table;
pub mod hanzi_map;
pub mod hanzi_embeddings;
pub mod embedding_observer;
pub mod operator_semantic;

pub use gua::Gua;
pub use cang_sea::CangSea;
pub use cang_sea::{CangSeaEntry, SemanticStore, SemanticEntry, MergeStrategy, project_embedding_to_bits};
pub use project_context::{ProjectContext, DecisionEntry};
pub use bagua::{Bagua, ZhouGrid};
pub use lianshan::{FangWei, SixQi, SixJia, SanYuan, LianShanInput, LianShanDecision, ZhiForces};
pub use deviation::{deviation, hybrid_deviation, DeviationSource};
pub use embedding::{Embedding, MockEncoder, MockEncoderMode, TextEncoder, cosine_similarity, advance_drift};
pub use semantic::{StrategyInput, StrategyOutput, SemanticDecision,
                   AttitudeInput, AttitudeOutput, AttitudeEncoder};
pub use yin_checker::{YinProtocolChecker, OperatorRule, RuleResult, OutputStructure};
pub use constraint_text::{SAN_YI_CONSTRAINT_FULL_TEXT, DynamicPromptState, build_sanyi_dynamic_prompt, fangwei_strategic_guidance, operator_actionable_guidance};
pub use context_metabolism::{ContextMetabolism, MetabolismEntry, MetabolismQuality};
pub use hanzi_table::{HanziEntry, HanziCategory, WuXing, lookup as lookup_hanzi};
pub use hanzi_map::{HanziMap, HanziMapping};
pub use hanzi_embeddings::HanziEmbeddings;
pub use embedding_observer::{EmbeddingObserver, Observation};
pub use operator_semantic::{OperatorSemanticAnchor, classify_operator_phase, classify_with_scores, build_operator_anchors};
